all: g2
	
g0:
	gcc -Wall -ansi -pedantic -ggdb0 -o maing0 main.c
	
g1:
	gcc -Wall -ansi -pedantic -ggdb1 -o maing1 main.c
	
g2:
	gcc -Wall -ansi -pedantic -ggdb2 -o maing2 main.c
	
g3:
	gcc -Wall -ansi -pedantic -ggdb3 -o maing3 main.c
	
run:
	./main
